# Site settings
title:       Bryce Holcomb
email:       brycecholcomb@gmail.com
author:      Bryce Holcomb
description: "Ramblings on Ruby, Rails and a little Javascript on the side"
baseurl:     ""
url:         "http://www.bryceholcomb.com"

# Google analytics
google_analytics:

#Projects settings
collections: [projects]

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: bryceholcomb
stackoverflow_id:
twitter_username: bryceholcomb1
google_plus_id:
linkedin_username: bryceholcomb
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
